version: 2.1
orbs:
  ruby: circleci/ruby@0.1.2 

executors:
  ruby:
    parameters:
      tag:
        type: string
        default: "latest"
    docker:
      - image: ruby:<< parameters.tag >>
    environment:
      BUNDLE_PATH: vendor/bundle
      BUNDLE_JOBS: 4
    working_directory: ~/app

jobs:
  rspec:
    parameters:
      version:
        type: string
    executor:
      name: ruby
      tag: << parameters.version >>
    steps:
      - checkout
      - run: ruby --version
      - run: bundle --version
      - run: gem --version
      - run: gem install bundler
      - run: bundle install --jobs 4
      - run: bundle exec rubocop
      - run: bundle exec rspec
      - run: bundle exec steep check

build_jobs: &build_jobs
  - rspec:
      matrix:
        parameters:
          version:
            - "2.7"
            - "3.0.1"
            - "3.0.2"
            - "3.1.0"
workflows:
  version: 2
  build:
    jobs: *build_jobs
